// examples/basics/try-catch-finally.sfn

fn main() {
    try {
        performRiskyOperation();
    } catch (err) {
        print.error("Something went wrong: {{err}}");
    } finally {
        print.info("Shutting down cleanly.");
    }
}
